export const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
export const GET_ALLPOKEMON = 'GET_ALLPOKEMON';
export const GET_POKEMON_TYPES = 'GET_POKEMON_TYPES';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
export const FILTER_BY_CREATED = 'FILTER_BY_CREATED';
export const FILTER_BY_ATTACK = 'FILTER_BY_ATTACK';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const POST_POKEMON = 'POST_POKEMON';